# -*- coding: utf-8 -*-
"""covid-19-svm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CNlaYpdya5LrHIXTqm1f1e1g_aVNrydo
"""

from sklearn import svm

# from UCSD dataset deep learning code
import torch
import torchvision
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torch.nn.functional as F
import torch.nn as nn
import torch.optim as optim
import os
import matplotlib.pyplot as plt
from torch.optim.lr_scheduler import StepLR
import numpy as np
from datetime import datetime
import pandas as pd
import random 
from torchvision.datasets import ImageFolder
import re
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
from PIL import Image
from torch.optim.lr_scheduler import StepLR
from sklearn.metrics import roc_auc_score
from skimage.io import imread, imsave
import skimage
from PIL import ImageFile
from PIL import Image

torch.cuda.empty_cache()

from google.colab import drive
drive.mount('/content/drive')

# link google drive and unzip image datasets
os.chdir('/content/drive/My Drive/cs168_final_project')
# !mkdir covid
# !mkdir noncovid
# !unzip -q CT_COVID.zip -d covid/
# !unzip -q CT_NonCOVID.zip -d noncovid/

normalize = transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
train_transformer = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomResizedCrop((224),scale=(0.5,1.0)),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    normalize
])

val_transformer = transforms.Compose([
    transforms.Resize(224),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    normalize
])

batchsize=4
def read_txt(txt_path):
    with open(txt_path) as f:
        lines = f.readlines()
    txt_data = [line.strip() for line in lines]
    return txt_data
    
class CovidCTDataset(Dataset):
    def __init__(self, root_dir, txt_COVID, txt_NonCOVID, transform=None):
        """
        Args:
            txt_path (string): Path to the txt file with annotations.
            root_dir (string): Directory with all the images.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        File structure:
        - root_dir
            - CT_COVID
                - img1.png
                - img2.png
                - ......
            - CT_NonCOVID
                - img1.png
                - img2.png
                - ......
        """
        self.root_dir = root_dir
        self.txt_path = [txt_COVID,txt_NonCOVID]
        self.classes = ['CT_COVID', 'CT_NonCOVID']
        self.num_cls = len(self.classes)
        self.img_list = []
        for c in range(self.num_cls):
            cls_list = [[os.path.join(self.root_dir,self.classes[c],item), c] for item in read_txt(self.txt_path[c])]
            self.img_list += cls_list
        self.transform = transform

    def __len__(self):
        return len(self.img_list)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()

        img_path = self.img_list[idx][0]
        image = Image.open(img_path).convert('RGB')

        if self.transform:
            image = self.transform(image)
        sample = {'img': image,
                  'label': int(self.img_list[idx][1])}
        return sample

trainset = CovidCTDataset(root_dir='/content/drive/My Drive/cs168_final_project/image_dataset',
                       txt_COVID='/content/drive/My Drive/cs168_final_project/Data-split/COVID/trainCT_COVID.txt',
                       txt_NonCOVID='/content/drive/My Drive/cs168_final_project/Data-split/NonCOVID/trainCT_NonCOVID.txt',
                       transform= train_transformer)
valset = CovidCTDataset(root_dir='/content/drive/My Drive/cs168_final_project/image_dataset',
                       txt_COVID='/content/drive/My Drive/cs168_final_project/Data-split/COVID/valCT_COVID.txt',
                       txt_NonCOVID='/content/drive/My Drive/cs168_final_project/Data-split/NonCOVID/valCT_NonCOVID.txt',
                       transform= val_transformer)
testset = CovidCTDataset(root_dir='/content/drive/My Drive/cs168_final_project/image_dataset',
                        txt_COVID='/content/drive/My Drive/cs168_final_project/Data-split/COVID/testCT_COVID.txt',
                        txt_NonCOVID='/content/drive/My Drive/cs168_final_project/Data-split/NonCOVID/testCT_NonCOVID.txt',
                        transform= val_transformer)
print(trainset.__len__())
print(valset.__len__())
print(testset.__len__())

train_loader = DataLoader(trainset, batch_size=batchsize, drop_last=False, shuffle=True)
val_loader = DataLoader(valset, batch_size=batchsize, drop_last=False, shuffle=False)
test_loader = DataLoader(testset, batch_size=batchsize, drop_last=False, shuffle=False)

# altering data to be compatable with sklearn's SVM package
trainY = []
trainX = []
for data in trainset:
  trainY.append(data["label"])
  trainX.append(data["img"].flatten().numpy())

valX = []
valY = []
for data in valset:
  valY.append(data["label"])
  valX.append(data["img"].flatten().numpy())

testX = []
testY = []
for data in valset:
  testY.append(data["label"])
  testX.append(data["img"].flatten().numpy())

# Commented out IPython magic to ensure Python compatibility.
from sklearn import datasets, svm, metrics

clf = svm.SVC(kernel='sigmoid')
clf.fit(trainX,trainY)
clf.fit(trainX,trainY)
predicted = clf.predict(testX)

print("Classification report for classifier %s:\n%s\n"
#       % (clf, metrics.classification_report(testY, predicted)))
disp = metrics.plot_confusion_matrix(clf, testX, testY)
disp.figure_.suptitle("Confusion Matrix")
print("Confusion matrix:\n%s" % disp.confusion_matrix)

plt.show()

print(predicted)
print(testY)

# Commented out IPython magic to ensure Python compatibility.
clf_rbf = svm.SVC(kernel='rbf')
clf_rbf.fit(trainX,trainY)
clf_rbf.fit(trainX,trainY)
predicted_rbf = clf_rbf.predict(testX)

print("Classification report for classifier %s:\n%s\n"
#       % (clf_rbf, metrics.classification_report(testY, predicted_rbf)))
disp_rbf = metrics.plot_confusion_matrix(clf_rbf, testX, testY)
disp_rbf.figure_.suptitle("Confusion Matrix")
print("Confusion matrix:\n%s" % disp_rbf.confusion_matrix)

plt.show()

print(predicted_rbf)
print(testY)

# Commented out IPython magic to ensure Python compatibility.
clf_linear = svm.SVC(kernel='linear')
clf_linear.fit(trainX,trainY)
clf_linear.fit(trainX,trainY)
predicted_linear = clf_linear.predict(testX)

print("Classification report for classifier %s:\n%s\n"
#       % (clf_linear, metrics.classification_report(testY, predicted_linear)))
disp_linear = metrics.plot_confusion_matrix(clf_linear, testX, testY)
disp_linear.figure_.suptitle("Confusion Matrix")
print("Confusion matrix:\n%s" % disp_linear.confusion_matrix)

plt.show()

print(predicted_linear)
print(testY)